[package]
name = "dumb_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5" , features = ["json"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
tokio = { version = "1.39.2", features = ["full"] }
